### ISSUE TITLE
Conv layer does not get initialized.

### ISSUE THREAD

**Issue by hardik-kansal** [storswiftlabs/convolution#1]
In examples/cnn/main.nr

    let weight1 = Tensor::new_quantized(w1, [5, 1, 3, 3], zero_point, scale);
    let bias1 = Tensor::new_quantized(b1, [1, 5], zero_point, scale);
    let weight2 = Tensor::new_quantized(w2, [10, 1, 3, 3], zero_point, scale);
    let bias2 = Tensor::new_quantized(b2, [1, 10], zero_point, scale);
    let weight3 = Tensor::new_quantized(w3, [49, 10], zero_point, scale);
    let bias3 = Tensor::new_quantized(b3, [1, 10], zero_point, scale);

    let conv_layer1 = Conv2D::new(weight1, bias1, 1, 1);
    let conv_layer2 = Conv2D::new(weight2, bias2, 1, 1);

conv_layer1 and conv_layer2 does not get initialized properly. I am constantly getting error :

error: Expected type Tensor<_, 4>, found type Tensor<45, 4>
error: Expected type Tensor<_, 2>, found type Tensor<5, 2>

Please look into this issue.

**Comment by huangliang-hl** [comment]
https://github.com/storswiftlabs/convolution/commit/29548dc42b0f1aead94270cc2df671cfbdedec1b
